language: node_js
node_js:
  - "14"
before_install:
  - git fetch --unshallow || true
install:
  - yarn install --frozen-lockfile
script:
  - npm run build
  - npm run lint
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8